select = [
  "E", # pycodestyle
  "W", # pycodestyle
  "F", # pyflakes
  "C90", # mccabe
  "I", # isort
  "UP", # pyupgrade
  "N", # pep8-naming
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "PT", # flake8-pytest-style
  "ARG", # flake8-unused-arguments
  "PD", # pandas-vet
  "RUF" # ruff
]
fixable = ["I", "UP", "C4"]
force-exclude = true

[isort]
force-single-line = true

[per-file-ignores]
"tests*" = ["ARG"]

[flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]
